version: '3.9'

services:
  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8200:8200"
    networks:
      - tfm-net
    volumes:
      - keycloak_data:/opt/keycloak/data
      - vault_data:/vault/data
    restart: always

  app-home:
    container_name: app-home
    build:
      context: ./app-home
      dockerfile: Dockerfile    
    ports:
      - "8088:80"
    networks:
      - tfm-net
    restart: always

  phpmyadmin:
    container_name: phpmyadmin
    build:
      context: ./db/phpmyadmin
      dockerfile: Dockerfile
    ports:
      - "8880:80"
    networks:
      - tfm-net
    volumes:
      - phpmyadmin_data:/etc/phpmyadmin
    restart: always

  db:
    container_name: mysql
    build:
      context: ./db/mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tfm-net
    restart: always
  
  linear-regression:
    container_name: linear-regression
    build:
      context: ./linear-regression
      dockerfile: Dockerfile    
    ports:
      - "5000:5000"
    networks:
      - tfm-net
    restart: always

  logistic-regression:
    container_name: logistic-regression
    build:
      context: ./logistic-regression
      dockerfile: Dockerfile    
    ports:
      - "5001:5001"
    networks:
      - tfm-net
    restart: always

  random-forest:
    container_name: random-forest
    build:
      context: ./random-forest
      dockerfile: Dockerfile    
    ports:
      - "5002:5002"
    networks:
      - tfm-net
    restart: always

networks:
  tfm-net:

volumes:
  keycloak_data:
  vault_data:
  phpmyadmin_data:
  db_data: